import { test, expect } from '@playwright/test';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
const proofFile=process.env.AIDE_WORKSTATION_E2E_PAIRING_PROOF;
const workspace=process.env.AIDE_WORKSTATION_E2E_WORKSPACE;
if(!proofFile||!workspace)throw new Error('isolated workstation fixture unavailable');
test('Cipher Laptop shows real governed file lineage and preserves it across window lifecycle and browser restart',async({page})=>{
 let proof=await fs.readFile(proofFile+'.laptop','utf8');let token:string|null=null;const errors:string[]=[];
 page.on('pageerror',error=>errors.push(error.message));
 page.on('dialog',dialog=>dialog.type()==='prompt'?dialog.accept(proof):dialog.type()==='confirm'?dialog.accept():dialog.dismiss());
 await page.route('**/api/authority/pair',async route=>{
  const response=await route.fetch();const envelope=await response.json() as {data?:{token?:string}};
  token=envelope.data?.token??null;await route.fulfill({response,body:JSON.stringify(envelope)});
 });
 await page.addInitScript(()=>{(globalThis as typeof globalThis & {__AIDE_RUNTIME_CONFIG__?:{facadeOrigin:string}}).__AIDE_RUNTIME_CONFIG__={facadeOrigin:window.location.origin};});
 await page.goto('/');await page.getByRole('button',{name:'Pair browser session',exact:true}).click();
 await expect.poll(()=>token!==null).toBe(true);await expect(page.locator('[aria-label="Authority paired: PAIRED"]')).toBeVisible();
 const taskId=randomUUID(),filename='laptop-'+taskId+'.txt',marker='CIPHER_LAPTOP_REAL_'+taskId;
 const send=async(route:string,body:unknown,headers:Record<string,string>={})=>{
  const result=await page.evaluate(async({route,body,headers,token})=>{
   const response=await fetch(route,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','X-AIDE-API-Format':'envelope-v1',...headers},body:JSON.stringify(body)});
   return {status:response.status,envelope:await response.json() as {ok:boolean;data?:{operation_id:string};error?:{code:string}}};
  },{route,body,headers,token});
  expect(result.status,route+' '+(result.envelope.error?.code??'')).toBe(200);expect(result.envelope.ok).toBe(true);return result.envelope.data;
 };
 const body={path:filename,content:marker,approved:true};
 const prepared=await send('/api/authority/prepare',{method:'POST',path:'/api/file/write',task_id:taskId,body});
 if(!prepared)throw new Error('operation owner unavailable');const actionId=prepared.operation_id;
 await send('/api/authority/decision',{operation_id:actionId,decision:'approve'});
 await send('/api/file/write',body,{'X-AIDE-Operation':actionId,'X-AIDE-Task':taskId});
 expect(await fs.readFile(path.join(workspace!,filename),'utf8')).toBe(marker);
 await expect(page.locator('.desktop-window[data-instance-id="terminal"] .terminal-provider.selected')).toBeVisible();
 const terminalPalette=await page.locator('.desktop-window[data-instance-id="terminal"] .terminal-panel').evaluate(node=>{
  const expected=document.createElement('span');expected.style.color='var(--desktop-accent)';node.append(expected);
  const title=node.querySelector('.panel-section-title'),selected=node.querySelector('.terminal-provider.selected');
  const color=getComputedStyle(expected).color;expected.remove();
  return {title:title?getComputedStyle(title).color:null,selected:selected?getComputedStyle(selected).outlineColor:null,expected:color};
 });
 expect(terminalPalette.title).toBe(terminalPalette.expected);expect(terminalPalette.selected).toBe(terminalPalette.expected);
 await page.keyboard.press('Alt+9');
 const laptop=page.locator('.desktop-window[data-app-id="cipher-laptop"]');
 await expect(laptop).toBeVisible();await laptop.getByRole('button',{name:'Refresh Cipher Laptop',exact:true}).click();await expect(laptop.locator('.cipher-laptop-status')).toContainText('HASH_CHAIN_VERIFIED');
 const rows=laptop.locator('tbody tr').filter({hasText:actionId});await expect(rows).toHaveCount(4);
 for(const stage of ['PREPARE','AUTHORITY_DECISION','EFFECT_ATTEMPT','OBSERVATION'])await expect(rows.filter({hasText:stage})).toHaveCount(1);
 await expect(rows.filter({hasText:'OBSERVATION'})).toContainText('OBSERVED');
 await laptop.getByRole('button',{name:'INTEGRITY',exact:true}).click();await expect(laptop).toContainText('SIGNATURE_UNAVAILABLE');
 await page.screenshot({path:test.info().outputPath('covert-cipher-laptop-integrity.png'),fullPage:true});
 await laptop.getByRole('button',{name:'ACTIVITY',exact:true}).click();
 await laptop.getByRole('button',{name:'Minimize window',exact:true}).click();await expect(laptop).toBeHidden();
 await page.getByRole('button',{name:'Focus or restore Cipher Laptop, minimized',exact:true}).click();await expect(laptop).toBeVisible();
 await laptop.getByRole('button',{name:'Close window',exact:true}).click();await expect(laptop).toHaveCount(0);
 await page.keyboard.press('Alt+9');await expect(rows).toHaveCount(4);
 proof=await fs.readFile(proofFile+'.laptop-restart','utf8');
 await page.reload();await expect(laptop).toBeVisible();
 await laptop.getByRole('button',{name:'Minimize window',exact:true}).click();
 await page.getByRole('button',{name:'Pair browser session',exact:true}).click();await expect(page.locator('[aria-label="Authority paired: PAIRED"]')).toBeVisible();
 await page.getByRole('button',{name:'Focus or restore Cipher Laptop, minimized',exact:true}).click();
 await laptop.getByRole('button',{name:'Refresh Cipher Laptop',exact:true}).click();await expect(rows).toHaveCount(4);
 await page.screenshot({path:test.info().outputPath('covert-cipher-laptop-activity.png'),fullPage:true});
 await laptop.getByRole('button',{name:'NOTEBOOK',exact:true}).click();
 await laptop.getByRole('textbox',{name:'Notebook record identity',exact:true}).fill('operator.runtime');
 await laptop.getByRole('textbox',{name:'Notebook approved content',exact:true}).fill('Attach evidence and challenge assumptions.');
 await laptop.getByRole('checkbox',{name:'I approve retaining this working record',exact:true}).check();
 await laptop.getByRole('button',{name:'SAVE RECORD',exact:true}).click();
 const record=laptop.locator('.cipher-notebook-record').filter({hasText:'operator.runtime'});await expect(record).toContainText('revision 1');
 await record.getByRole('button',{name:'CORRECT',exact:true}).click();
 await laptop.getByRole('textbox',{name:'Notebook approved content',exact:true}).fill('Prefer concise evidence.');
 await laptop.getByRole('checkbox',{name:'I approve retaining this working record',exact:true}).check();
 await laptop.getByRole('button',{name:'SAVE CORRECTION',exact:true}).click();await expect(record).toContainText('revision 2');
 await page.screenshot({path:test.info().outputPath('covert-cipher-laptop-notebook.png'),fullPage:true});
 await record.getByRole('button',{name:'REMOVE',exact:true}).click();await expect(record).toHaveCount(0);
 const notebook=await fs.readFile(path.join(workspace!,'.aide','cipher-laptop','notebook.json'),'utf8');
 expect(notebook).not.toContain('Prefer concise evidence.');expect(notebook).not.toContain('Attach evidence and challenge assumptions.');
 expect(errors).toEqual([]);
});