import test from 'node:test';
import assert from 'node:assert/strict';
import { TerminalSessionService } from '../../node/src/services/terminal-sessions.ts';
class Pty {
 onData(callback){this.data=callback;} onExit(callback){this.exit=callback;} write(){} resize(){} kill(){this.exit?.({exitCode:0});}
}
function fixture(){const events=[],ptys=[];const service=new TerminalSessionService({defaultCwd:process.cwd(),drainIntervalMs:5,onEvent:(event,owner)=>events.push({event,owner}),spawnOverride:()=>{const pty=new Pty();ptys.push(pty);return pty;},deps:{platform:'win32',loadPty:()=>({spawn(){throw Error('real PTY prohibited in unit test');}}),fileExists:async()=>true,listDir:async()=>[],exec:async()=>({code:0,stdout:'',stderr:''})}});return{service,events,ptys};}
async function open(f,owner='operator:a'){const result=await f.service.open({owner,provider:'native',shell:'powershell',cwd:null,cols:120,rows:40});assert.ok(!('error'in result));return result.session.sessionId;}
test('approved service resume returns bounded replay even without a subscribed event socket',async()=>{const f=fixture();try{const id=await open(f);f.ptys[0].data('undelivered output');const resumed=f.service.resume('operator:b',id,'operator:a');assert.equal(resumed.output.output,'undelivered output');assert.equal(resumed.output.endOffset,18);assert.equal(f.ptys.length,1);}finally{f.service.stopAll();}});
test('snapshot offsets fence undrained output and owner reads refuse foreign callers',async()=>{const f=fixture();try{const id=await open(f);f.ptys[0].data('exactly once');const resumed=f.service.resume('operator:b',id,'operator:a');await new Promise(resolve=>setTimeout(resolve,20));const frames=f.events.filter(item=>item.owner==='operator:b'&&item.event.kind==='output').map(item=>item.event);assert.ok(frames.every(frame=>frame.endOffset<=resumed.output.endOffset));assert.ok('error'in f.service.outputSnapshot('operator:a',id));assert.equal(f.service.outputSnapshot('operator:b',id).output,'exactly once');}finally{f.service.stopAll();}});
test('finished sessions discard replay buffers while live replay remains available',async()=>{const f=fixture();try{for(let index=0;index<20;index++){const id=await open(f);f.ptys.at(-1).data('x'.repeat(20000));f.ptys.at(-1).kill();assert.equal(f.service.outputSnapshot('operator:a',id).output,'');}const live=await open(f);f.ptys.at(-1).data('live retained');assert.equal(f.service.outputSnapshot('operator:a',live).output,'live retained');}finally{f.service.stopAll();}});
