import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import ts from 'typescript';
import { readFile } from 'node:fs/promises';
const source=await readFile(new URL('../../browser/src/services/ws.ts',import.meta.url),'utf8');
const script=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
function fixture(){const sockets=[];let authentications=0;class Socket{static OPEN=1;constructor(){this.readyState=1;this.listeners={};this.sent=[];sockets.push(this);}addEventListener(type,callback){this.listeners[type]=callback;}send(data){this.sent.push(JSON.parse(data));}close(){this.listeners.close?.();}receive(data){this.listeners.message?.({data:JSON.stringify(data)});}}const exports={};const ports={'../../../common/contracts/events.ts':{EventEnvelope:{safeParse:()=>({success:false})}},'./authority.ts':{authenticateEventSocket:()=>{authentications++;}}};vm.runInNewContext(script,{exports,require:name=>ports[name],WebSocket:Socket,setTimeout:()=>1,clearTimeout(){},Math});const bus=exports.connectEvents('ws://fixture.invalid');return{bus,sockets,get authentications(){return authentications;}};}
test('output recovery waits for an authenticated acknowledged terminal subscription',()=>{const f=fixture();let ready=0;f.bus.subscribe('terminal',()=>{});f.bus.onSubscribed('terminal',()=>ready++);const socket=f.sockets[0];socket.receive({type:'subscribed',channels:['terminal']});assert.equal(ready,0);socket.listeners.open();assert.equal(f.authentications,1);socket.receive({type:'authenticated'});assert.equal(f.bus.connected(),true);assert.equal(ready,0);assert.ok(socket.sent.some(message=>message.type==='subscribe'));socket.receive({type:'subscribed',channels:['other']});assert.equal(ready,0);socket.receive({type:'subscribed',channels:['terminal']});assert.equal(ready,1);f.bus.dispose();});
test('disconnect surfaces stale transport and unsubscribe/dispose prevent late recovery callbacks',()=>{const f=fixture();const states=[];f.bus.subscribe('terminal',()=>{});f.bus.subscribeStatus(value=>states.push(value));let ready=0;const unsubscribe=f.bus.onSubscribed('terminal',()=>ready++);const socket=f.sockets[0];socket.receive({type:'authenticated'});socket.receive({type:'subscribed',channels:['terminal']});unsubscribe();socket.receive({type:'subscribed',channels:['terminal']});assert.equal(ready,1);socket.close();assert.equal(f.bus.connected(),false);assert.deepEqual(states,[true,false]);f.bus.dispose();socket.receive({type:'subscribed',channels:['terminal']});assert.equal(ready,1);});
