[package]
name = "aide-sovereign-workbench"
version = "0.1.0"
description = "Covert Coder desktop shell"
authors = ["Ferrell Synthetic Intelligence"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dunce = "=1.0.5"
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
